old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.notification_producer' service to send data.
        notification:
            connection:       default
            exchange_options: { name: 'notification', type: direct }
    consumers:
        notification:
            connection:       default
            exchange_options: { name: 'notification', type: direct }
            queue_options:    { name: 'notification'}
            callback:         App\Infrastructure\Amqp\NotificationConsumer
